version: "3.4"

services:
  api:
    container_name: be-temanikah
    build:
      context: .
      target: production
    volumes:
      - ./logs:/usr/src/app/logs
      - ./public:/usr/src/app/public
    ports:
      - 5000:5000
